### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by rendinam** [rendinam/auto-test#1]
Test issue text.

**Comment by rendinam** [comment]
New comment here added via API.

**Comment by rendinam** [comment]
`cfitsio`
Version 3.45 - May 2018
                   
  - New support for reading and writing unsigned long long datatypes.
    This includes 'implicit datatype conversion' between the unsigned long
    long datatype and all the other datatypes.
    
  - Increased the hardcoded NMAXFILES setting for maximum number of
    open files from 1000 to 10000.
                   
  - Bug fix to fits_calc_binning wrapper function, which wasn't filling
    in the returned float variables.
    
  - Fixed a parsing bug for image subsection and column binning range
    specifiers that was introduced in v3.44.

**NOTE: This release introduces a SONAME change from 6 to 7.**
Software that depends upon cfitsio will need to be rebuilt to maintain compatibility.

**Comment by rendinam** [comment]
`cfitsio`
Version 3.45 - May 2018
                   
  - New support for reading and writing unsigned long long datatypes.
    This includes 'implicit datatype conversion' between the unsigned long
    long datatype and all the other datatypes.
    
  - Increased the hardcoded NMAXFILES setting for maximum number of
    open files from 1000 to 10000.
                   
  - Bug fix to fits_calc_binning wrapper function, which wasn't filling
    in the returned float variables.
    
  - Fixed a parsing bug for image subsection and column binning range
    specifiers that was introduced in v3.44.


**NOTE: This release introduces a SONAME change from 6 to 7.**

**Comment by rendinam** [comment]
`cfitsio`
Version 3.45 - May 2018
                   
  - New support for reading and writing unsigned long long datatypes.
    This includes 'implicit datatype conversion' between the unsigned long
    long datatype and all the other datatypes.
    
  - Increased the hardcoded NMAXFILES setting for maximum number of
    open files from 1000 to 10000.
                   
  - Bug fix to fits_calc_binning wrapper function, which wasn't filling
    in the returned float variables.
    
  - Fixed a parsing bug for image subsection and column binning range
    specifiers that was introduced in v3.44.


**NOTE: This release introduces a SONAME change from 6 to 7.**

**Comment by rendinam** [comment]
`cfitsio`
Version 3.45 - May 2018
                   
  - New support for reading and writing unsigned long long datatypes.
    This includes 'implicit datatype conversion' between the unsigned long
    long datatype and all the other datatypes.
    
  - Increased the hardcoded NMAXFILES setting for maximum number of
    open files from 1000 to 10000.
                   
  - Bug fix to fits_calc_binning wrapper function, which wasn't filling
    in the returned float variables.
    
  - Fixed a parsing bug for image subsection and column binning range
    specifiers that was introduced in v3.44.


**NOTE: This release introduces a SONAME change from 6 to 7.**

**Comment by rendinam** [comment]
`cfitsio`
Version 3.45 - May 2018
                   
  - New support for reading and writing unsigned long long datatypes.
    This includes 'implicit datatype conversion' between the unsigned long
    long datatype and all the other datatypes.
    
  - Increased the hardcoded NMAXFILES setting for maximum number of
    open files from 1000 to 10000.
                   
  - Bug fix to fits_calc_binning wrapper function, which wasn't filling
    in the returned float variables.
    
  - Fixed a parsing bug for image subsection and column binning range
    specifiers that was introduced in v3.44.


**NOTE: This release introduces a SONAME change from 6 to 7.**

**Comment by rendinam** [comment]
`cfitsio`
Version 3.45 - May 2018
                   
  - New support for reading and writing unsigned long long datatypes.
    This includes 'implicit datatype conversion' between the unsigned long
    long datatype and all the other datatypes.
    
  - Increased the hardcoded NMAXFILES setting for maximum number of
    open files from 1000 to 10000.
                   
  - Bug fix to fits_calc_binning wrapper function, which wasn't filling
    in the returned float variables.
    
  - Fixed a parsing bug for image subsection and column binning range
    specifiers that was introduced in v3.44.


**NOTE: This release introduces a SONAME change from 6 to 7.**

**Comment by rendinam** [comment]
`cfitsio`
Version 3.45 - May 2018
                   
  - New support for reading and writing unsigned long long datatypes.
    This includes 'implicit datatype conversion' between the unsigned long
    long datatype and all the other datatypes.
    
  - Increased the hardcoded NMAXFILES setting for maximum number of
    open files from 1000 to 10000.
                   
  - Bug fix to fits_calc_binning wrapper function, which wasn't filling
    in the returned float variables.
    
  - Fixed a parsing bug for image subsection and column binning range
    specifiers that was introduced in v3.44.


**NOTE: This release introduces a SONAME change from 6 to 7.**

**Comment by rendinam** [comment]
`cfitsio`
Version 3.45 - May 2018
                   
  - New support for reading and writing unsigned long long datatypes.
    This includes 'implicit datatype conversion' between the unsigned long
    long datatype and all the other datatypes.
    
  - Increased the hardcoded NMAXFILES setting for maximum number of
    open files from 1000 to 10000.
                   
  - Bug fix to fits_calc_binning wrapper function, which wasn't filling
    in the returned float variables.
    
  - Fixed a parsing bug for image subsection and column binning range
    specifiers that was introduced in v3.44.


**NOTE: This release introduces a SONAME change from 6 to 7.**

**Comment by rendinam** [comment]
`cfitsio`
Version 3.45 - May 2018
                   
  - New support for reading and writing unsigned long long datatypes.
    This includes 'implicit datatype conversion' between the unsigned long
    long datatype and all the other datatypes.
    
  - Increased the hardcoded NMAXFILES setting for maximum number of
    open files from 1000 to 10000.
                   
  - Bug fix to fits_calc_binning wrapper function, which wasn't filling
    in the returned float variables.
    
  - Fixed a parsing bug for image subsection and column binning range
    specifiers that was introduced in v3.44.


**NOTE: This release introduces a SONAME change from 6 to 7.**

**Comment by rendinam** [comment]
This is a message from an automated system that monitors `cfitsio` releases.
`cfitsio`Version 3.45 - May 2018
                   
  - New support for reading and writing unsigned long long datatypes.
    This includes 'implicit datatype conversion' between the unsigned long
    long datatype and all the other datatypes.
    
  - Increased the hardcoded NMAXFILES setting for maximum number of
    open files from 1000 to 10000.
                   
  - Bug fix to fits_calc_binning wrapper function, which wasn't filling
    in the returned float variables.
    
  - Fixed a parsing bug for image subsection and column binning range
    specifiers that was introduced in v3.44.


**NOTE: This release introduces a SONAME change from 6 to 7.**

**Comment by rendinam** [comment]
This is a message from an automated system that monitors `cfitsio` releases.
`cfitsio`Version 3.45 - May 2018
                   
  - New support for reading and writing unsigned long long datatypes.
    This includes 'implicit datatype conversion' between the unsigned long
    long datatype and all the other datatypes.
    
  - Increased the hardcoded NMAXFILES setting for maximum number of
    open files from 1000 to 10000.
                   
  - Bug fix to fits_calc_binning wrapper function, which wasn't filling
    in the returned float variables.
    
  - Fixed a parsing bug for image subsection and column binning range
    specifiers that was introduced in v3.44.


**NOTE: This release introduces a SONAME change from 6 to 7.**

**Comment by rendinam** [comment]
This is a message from an automated system that monitors `cfitsio` releases.
`cfitsio`Version 3.45 - May 2018
                   
  - New support for reading and writing unsigned long long datatypes.
    This includes 'implicit datatype conversion' between the unsigned long
    long datatype and all the other datatypes.
    
  - Increased the hardcoded NMAXFILES setting for maximum number of
    open files from 1000 to 10000.
                   
  - Bug fix to fits_calc_binning wrapper function, which wasn't filling
    in the returned float variables.
    
  - Fixed a parsing bug for image subsection and column binning range
    specifiers that was introduced in v3.44.


**NOTE: This release introduces a SONAME change from 6 to 7.**

**Comment by rendinam** [comment]
This is a message from an automated system that monitors `cfitsio` releases.
`cfitsio`Version 3.45 - May 2018
                   
  - New support for reading and writing unsigned long long datatypes.
    This includes 'implicit datatype conversion' between the unsigned long
    long datatype and all the other datatypes.
    
  - Increased the hardcoded NMAXFILES setting for maximum number of
    open files from 1000 to 10000.
                   
  - Bug fix to fits_calc_binning wrapper function, which wasn't filling
    in the returned float variables.
    
  - Fixed a parsing bug for image subsection and column binning range
    specifiers that was introduced in v3.44.


**NOTE: This release introduces a SONAME change from 6 to 7.**

**Comment by rendinam** [comment]
This is a message from an automated system that monitors `cfitsio` releases.
`cfitsio`Version 3.45 - May 2018
                   
  - New support for reading and writing unsigned long long datatypes.
    This includes 'implicit datatype conversion' between the unsigned long
    long datatype and all the other datatypes.
    
  - Increased the hardcoded NMAXFILES setting for maximum number of
    open files from 1000 to 10000.
                   
  - Bug fix to fits_calc_binning wrapper function, which wasn't filling
    in the returned float variables.
    
  - Fixed a parsing bug for image subsection and column binning range
    specifiers that was introduced in v3.44.


**NOTE: This release introduces a SONAME change from 6 to 7.**

**Comment by rendinam** [comment]
This is a message from an automated system that monitors `cfitsio` releases.
`cfitsio`Version 3.45 - May 2018
                   
  - New support for reading and writing unsigned long long datatypes.
    This includes 'implicit datatype conversion' between the unsigned long
    long datatype and all the other datatypes.
    
  - Increased the hardcoded NMAXFILES setting for maximum number of
    open files from 1000 to 10000.
                   
  - Bug fix to fits_calc_binning wrapper function, which wasn't filling
    in the returned float variables.
    
  - Fixed a parsing bug for image subsection and column binning range
    specifiers that was introduced in v3.44.


**NOTE: This release introduces a SONAME change from 6 to 7.**

**Comment by rendinam** [comment]
This is a message from an automated system that monitors `cfitsio` releases.
`cfitsio`Version 3.45 - May 2018
                   
  - New support for reading and writing unsigned long long datatypes.
    This includes 'implicit datatype conversion' between the unsigned long
    long datatype and all the other datatypes.
    
  - Increased the hardcoded NMAXFILES setting for maximum number of
    open files from 1000 to 10000.
                   
  - Bug fix to fits_calc_binning wrapper function, which wasn't filling
    in the returned float variables.
    
  - Fixed a parsing bug for image subsection and column binning range
    specifiers that was introduced in v3.44.


**NOTE: This release introduces a SONAME change from 6 to 7.**

**Comment by rendinam** [comment]
This is a message from an automated system that monitors `cfitsio` releases.
`cfitsio`Version 3.45 - May 2018
                   
  - New support for reading and writing unsigned long long datatypes.
    This includes 'implicit datatype conversion' between the unsigned long
    long datatype and all the other datatypes.
    
  - Increased the hardcoded NMAXFILES setting for maximum number of
    open files from 1000 to 10000.
                   
  - Bug fix to fits_calc_binning wrapper function, which wasn't filling
    in the returned float variables.
    
  - Fixed a parsing bug for image subsection and column binning range
    specifiers that was introduced in v3.44.


**NOTE: This release introduces a SONAME change from 6 to 7.**

**Comment by rendinam** [comment]
This is a message from an automated system that monitors `cfitsio` releases.
`cfitsio`Version 3.45 - May 2018
                   
  - New support for reading and writing unsigned long long datatypes.
    This includes 'implicit datatype conversion' between the unsigned long
    long datatype and all the other datatypes.
    
  - Increased the hardcoded NMAXFILES setting for maximum number of
    open files from 1000 to 10000.
                   
  - Bug fix to fits_calc_binning wrapper function, which wasn't filling
    in the returned float variables.
    
  - Fixed a parsing bug for image subsection and column binning range
    specifiers that was introduced in v3.44.


**NOTE: This release introduces a SONAME change from 6 to 7.**

**Comment by st-automaton-01** [comment]
This is a message from an automated system that monitors `cfitsio` releases.
`cfitsio`Version 3.45 - May 2018
                   
  - New support for reading and writing unsigned long long datatypes.
    This includes 'implicit datatype conversion' between the unsigned long
    long datatype and all the other datatypes.
    
  - Increased the hardcoded NMAXFILES setting for maximum number of
    open files from 1000 to 10000.
                   
  - Bug fix to fits_calc_binning wrapper function, which wasn't filling
    in the returned float variables.
    
  - Fixed a parsing bug for image subsection and column binning range
    specifiers that was introduced in v3.44.


**NOTE: This release introduces a SONAME change from 6 to 7.**

**Comment by st-automaton-01** [comment]
This is a message from an automated system that monitors `cfitsio` releases.
`cfitsio`  Version 3.45 - May 2018
                   
  - New support for reading and writing unsigned long long datatypes.
    This includes 'implicit datatype conversion' between the unsigned long
    long datatype and all the other datatypes.
    
  - Increased the hardcoded NMAXFILES setting for maximum number of
    open files from 1000 to 10000.
                   
  - Bug fix to fits_calc_binning wrapper function, which wasn't filling
    in the returned float variables.
    
  - Fixed a parsing bug for image subsection and column binning range
    specifiers that was introduced in v3.44.


**NOTE: This release introduces a SONAME change from 6 to 7.**
